---
title: "Baseball Hall of Fame: Model Explorer"
author: "Andy, Dante, Kai, Kobe"
date: "2/26/2023"
output: 
  html_document:
    theme: flatly
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(tidyverse)
library(rvest)
library(flexdashboard)

PredictHOF_pos_df <- read.csv("data/PredictHOF_pos_df.csv") %>% 
  filter(votedBy == "BBWAA")
PredictHOF_pitch_df <- read.csv("data/PredictHOF_pitch_df.csv") %>% 
  filter(votedBy == "BBWAA")

PredictHOF_pos_df$Steroids <- as.factor(PredictHOF_pos_df$Steroids)

final_pos_glm <- readRDS("data/final_pos_glm.RDS")
final_pitch_glm <- readRDS("data/final_pitch_glm.RDS")

url <- "https://www.baseball-reference.com/players/%s.shtml"

get_profile <- function(playerID) {
  headshot <- sprintf(url, paste0(str_sub(playerID, 1, 1), "/", playerID)) %>%
    read_html() %>%
    html_node(css = 'div[class="media-item multiple"] img') %>%
    html_attr("src")

  return(headshot)
}
```

```{r echo=FALSE}
observeEvent(input$type, {
  choices <- NA
  df <- NA
  if (input$type == "Position") {
    df <- PredictHOF_pos_df 
  } else {
    df <- PredictHOF_pitch_df 
  }
  
  choices <- paste0(df$Player, ", ", df$playerID)
  updateSelectizeInput(session, inputId = "player", choices = choices, selected = choices[1])
})

observeEvent(input$player, {
  if (input$player != "") {
    id <- str_split(input$player, ", ")[[1]][2]
    name <- str_split(input$player, ", ")[[1]][1]
    text <- NA
    prob <- NA
    if (input$type == "Position") {
      newdat <- PredictHOF_pos_df %>%
        filter(playerID == !!id)
        
      prob <- predict(final_pos_glm, newdata = newdat, type = "response")
      
      text <- paste0(name, " has a ", round((as.numeric(prob))*100, 2), "% chance of making it to the HoF")
    } else {
      newdat <- PredictHOF_pitch_df %>%
        filter(playerID == !!id)
      
      prob <- predict(final_pitch_glm, newdata = newdat, type = "response")
      
      text <- paste0(name, " has a ", round((as.numeric(prob))*100, 2), "% chance of making it to the HoF")
    }
    
    headshot <- get_profile(id)
    
    if(is.na(headshot)) {
      headshot <- "https://usatodayhss.com/wp-content/uploads/sites/96/2018/08/screen-shot-2018-08-13-at-12-52-49-am.jpg"
    }
    
    removeUI("#pfp img")
    removeUI("#pname")

    insertUI(
      selector = "#pfp", "afterBegin",
      img(src=headshot, style = "height: 150px; border-radius: 5%")
    )

    insertUI(
      selector = "#gauge-desc", "afterBegin",
      p(id = "pname", style = "font-size: 20px;",name)
      # HTML(paste0("<p id='pname'>", name, "</p>"))
    )
    
    output$gauge = renderGauge({
    gauge(round((as.numeric(prob) * 100), 4), 
          min = 0, 
          max = 100.0, 
          sectors = gaugeSectors(success = c(80, 100), 
                                 warning = c(50, 80),
                                 danger = c(0, 50)))
  })
    
  }
})
```

```{r echo=FALSE}
tabsetPanel(
  tabPanel(
    "Player Search",
    sidebarLayout(
      sidebarPanel(
        width = 4,
        fluidRow(style = "padding: 2%",
    radioButtons("type", "Player Type:", 
                     c("Position", "Pitcher")),
        selectizeInput("player", "Player:", paste0(PredictHOF_pos_df$Player, ", ", PredictHOF_pos_df$playerID), selected = paste0(PredictHOF_pos_df$Player, ", ", PredictHOF_pos_df$playerID)[1]))
      ),
      mainPanel(width = 20,
                div(style = "margin-left: auto; margin-right: auto; fill: #",
                div(style = "display: flex; height: 300px; padding-top: 5%;",
                  id="psearch-card",
                  div(style="display: flex; flex-direction: column; align-items: center; justify-content: center; background-color: ", id = "gauge-desc",
                      em("HoF Chance"),
                      gaugeOutput("gauge", width = "50%")),
                  div(id="pfp", style = "width: 200px"))
                      )
      )
    )
),
tabPanel(
  "Custom Player",
  sidebarLayout(
    sidebarPanel(
      width = 4,
      fluidRow( 
  
                selectInput("pos", "Position:", choices = unique(PredictHOF_pos_df$Pos)),
                selectInput("votedby", "Voted By:", choices = unique(PredictHOF_pos_df$votedBy)),
                radioButtons("steroids", "Used Steroids:", choices = c("Yes", "No")),
                sliderInput("gs", "# of Games:", min = 0, max = 5000, value = 1000),
                sliderInput("avg", "Career AVG:", min = 0, max = 1, value = 0.5),
                sliderInput("slg", "Career SLG:", min = 0, max = 1, value = 0.5),
                sliderInput("hrs", "# of Career HRs:", min = 0, max = 500, value = 150),
                sliderInput("rbis", "# of Career RBIs:", min = 0, max = 2500, value = 300),
                sliderInput("runs", "# of Career Runs:", min = 0, max = 2500, value = 300),
                sliderInput("sbs", "# of Career SBs:", min = 0, max = 2000, value = 500),
                sliderInput("all_stars", "# of All Star Season:", min = 0, max = 30, value = 5),
                sliderInput("mvps", "# of Career MVPs:", min = 0, max = 10, value = 2),
                sliderInput("ggs", "# of Career Gold Gloves:", min = 0, max = 20, value = 2),
                sliderInput("ngas", "# of Career Nice Guy Awards:", min = 0, max = 20, value = 2),
                actionButton("submit", "Submit", onclick = "Shiny.onInputChange('myclick', submit)")
)
    ),
    mainPanel(
      width = 20
    )
  )
)
)

observeEvent(input$submit, {
  newdat <- list("all_star" = input$all_stars, Steroids = as.factor((input$steroids == "Yes")*1), "G" = input$gs, "HR" = input$hrs, "Pos" = input$pos, "votedBy" = input$votedby, "RBI" = input$rbis, "most_valuable_player" = input$mvps, "nice_guy_awards" = input$ngas, "gold_glove" = input$ggs, "R" = input$runs, "AVG" = input$avg, "SB" = input$sbs, "SLG" = input$slg)
  
      prob <- predict(final_pos_glm, newdata = newdat, type = "response")
      
      paste0("You have a ", round(as.numeric(prob)*100, 2), "% chance of making it to the HoF") %>% 
        modalDialog() %>% 
        showModal()
})
```

