---
title: "STAT423_Project1_Main"
author: "Dante Ramirez"
date: '2023-02-01'
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}

library(tidyverse)
library(Lahman)
library(readr)
library(lubridate)
library(GGally)
library(leaps)

# Please create a variable for all datasets below along with a message of what we need it for

# To find career position player numbers
batting_df <- read_csv(file = "Data/Batting2022updated.csv")

# To find career pitcher numbers
pitching_df <- read_csv(file = "Data/PitchingUpdated2022.csv")

# For our response of boolean elected into the hall or not
hall_df <- read_csv(file = "Data/HallOfFameUpdated2022.csv")

# For the WS win column
team_df <- read_csv(file = "Data/TeamsUpdated2022.csv")

# For awards won by players
awards_df <- read_csv(file = "Data/AwardsPlayers.csv")

# For allstar game appearences
allstar_df <- read_csv(file = "Data/AllstarFull.csv")

# Preleminary PED data frames
espn_ped_df <- read_csv(file = "Data/suspectedusers_espn.csv")
wiki_ped_df <- read_csv(file = "Data/suspendedlist_wikipedia.csv")

war_df_pos <- read_csv(file = "Data/posplayerWAR.csv")
colnames(war_df_pos)[1] ="playerID"

war_df_pitcher <- read_csv(file = "Data/pitcherWAR.csv")
colnames(war_df_pitcher)[1] ="playerID"

```

```{r combining hof mess, warning=FALSE, message=FALSE}

# Sums counting stats and removes categoricals
batting_df_continuous_counts <- batting_df %>%
  subset(select =-c(2:5)) %>% 
  group_by(playerID) %>%
  summarise(across(everything(), sum))

# Find the mode of most common team and league per player
batting_df_categorical_counts <- batting_df %>%
  subset(select = c(1,4,5)) %>%
  mutate(across(c(1:3), as.factor)) %>%
  group_by(playerID) %>%
  mutate(PrimaryTeam = names(which.max(table(teamID)))) %>%
  mutate(PrimaryLg = as.factor(names(which.max(table(lgID))))) %>%
  subset(select = c(1, 4, 5)) %>%
  distinct()

# Extract response y/n variable
hall_df_tidy <- hall_df %>%
  group_by(playerID) %>%
  subset(select = c(1, 3, 7, 8)) %>%
  filter(category == "Player")


# Sums counting stats for pitching
pitching_df_continuous_counts <- pitching_df %>%
  subset(select =-c(2:5, 19)) %>%
  group_by(playerID) %>%
  summarize(across(everything(), sum)) %>%
  mutate(ERA = round(ER / IPouts * 27, 2),
         WHIP = round((BB + H) / IPouts * 3, 2))

# Find the mode of most common team and league per pitcher
pitching_df_categorical_counts <- pitching_df %>%
  subset(select = c(1,4,5)) %>%
  mutate(across(c(1:3), as.factor)) %>%
  group_by(playerID) %>%
  mutate(PrimaryTeam = names(which.max(table(teamID)))) %>%
  mutate(PrimaryLg = as.factor(names(which.max(table(lgID))))) %>%
  subset(select = c(1, 4, 5)) %>%
  distinct()

# Unique HOF inducted and non-inducted players
hof_players <- hall_df %>% 
  filter(category == "Player") %>% 
  group_by(playerID) %>%
  summarize(wein = "Y" %in% inducted * 1, votedBy, yearID, maxYear = max(yearID)) %>%
  filter(yearID == maxYear) %>%
  select(-c(yearID, maxYear))

# Unique award winners -- columns represent different rewards
awards_new <- awards_df %>%
  filter(!(yearID < 1951 & awardID == "TSN All-Star"))
awards_new$awardID <- if_else(awards_new$awardID == "TSN All-Star" | awards_new$awardID == "Baseball Magazine All-Star", "All-Star", awards_new$awardID)
awards_wider <- awards_new %>% 
  mutate(award_id_clean = str_replace_all(str_replace_all(str_to_lower(awardID), " ", "_"), "-", "_")) %>% 
  group_by(playerID, award_id_clean) %>% 
  summarize(n = n()) %>%
  pivot_wider(id_cols = playerID, names_from = award_id_clean, values_from = n) %>% 
  mutate(across(1:28, ~ replace_na(.x, 0)))

espn_ped_df <- espn_ped_df %>%
  subset(select = c(2, 3)) %>% 
  rename(Player = name)

# For player name, debute, and playerID conversion
player_df <- read_csv(file = "Data/People2022.csv")

# Creates Player column to ease merging with other df's
player_df <- player_df %>% mutate(Player = str_c(nameFirst,
                                                 nameLast,
                                                 sep = " "))

# Main Pitcher data frame to preform analysis on
PitcherHOF_df <- inner_join(pitching_df_continuous_counts,
                                   pitching_df_categorical_counts,
                                   by = "playerID") %>%
  inner_join(awards_wider, by = "playerID") %>%
  inner_join(hof_players, by = "playerID") %>%
  filter(G > 200) %>%
  inner_join(player_df[, c(1, 25)], by = "playerID") %>%
  mutate(IP = IPouts / 3) %>%
  relocate(Player, .after = playerID) %>%
  relocate(IP, .after = IPouts) %>%
  mutate(Steroids = ifelse(Player %in% espn_ped_df$Player | Player %in% wiki_ped_df$Player, 1, 0)) %>%
  mutate(nice_guy_awards = lou_gehrig_memorial_award +
                           hutch_award +
                           roberto_clemente_award + 
                           branch_rickey_award) %>%
  left_join(war_df_pitcher, by = "playerID")

# Primary position by player
primary_position <- Appearances %>% 
  group_by(playerID) %>%
  summarize(P = sum(G_p), C = sum(G_c), `1B` = sum(G_1b), `2B` = sum(G_2b),
            `3B` = sum(G_3b), SS = sum(G_ss), RF = sum(G_rf), CF = sum(G_cf),
            LF = sum(G_lf), DH = sum(G_dh)) %>%
  pivot_longer(cols = c(P, C, `1B`, `2B`, `3B`, SS, RF, CF, LF, DH),
               names_to = "Pos") %>%
  group_by(playerID) %>%
  summarize(Pos = Pos, Value = value, Max = max(value)) %>%
  filter(Value == Max) %>%
  select(playerID, Pos)

# Main Position Player data frame to preform analysis on
PositionPlayerHOF_df <- inner_join(batting_df_continuous_counts,
                                   batting_df_categorical_counts,
                                   by = "playerID") %>%
  inner_join(awards_wider, by = "playerID") %>%
  inner_join(hof_players, by = "playerID") %>%
  subset(select = c(1:26, 28:31, 34:37, 40:42, 44, 45, 47, 49:50)) %>%
  mutate(across(c(19, 20, 29, 41), as.factor)) %>%
  filter(!(playerID %in% PitcherHOF_df$playerID)) %>%
  mutate(AVG = round(H / AB, 3), 
         OBP = round((H + BB + HBP) / (AB + ifelse(!is.na(SH), SH, 0) + ifelse(!is.na(SF), SF, 0) + BB + HBP), 3),
         `1B` = H - (`2B` + `3B` + HR),
         SLG = round((`1B` + `2B` * 2 + `3B` * 3 + HR * 4) / AB, 3)) %>%
  inner_join(player_df[, c(1, 25)], by = "playerID") %>%
  relocate(Player, .after = playerID) %>%
  mutate(Steroids = ifelse(Player %in% espn_ped_df$Player | Player %in% wiki_ped_df$Player, 1, 0)) %>%
  mutate(Steroids = as.factor(Steroids),
         nice_guy_awards = lou_gehrig_memorial_award +
                           hutch_award +
                           roberto_clemente_award + 
                           branch_rickey_award) %>%
  left_join(war_df_pos, by = "playerID") %>%
  distinct(playerID, .keep_all = TRUE) %>%
  mutate(votedBy = ifelse(Player == "Al Lopez", "Veterans",
                   ifelse(Player == "Charlie Gehringer", "BBWAA",
                   ifelse(Player == "Frank Chance", "Veterans",
                   ifelse(Player == "Fred Clark", "Veterans",
                   ifelse(Player == "Honus Wagner", "BBWAA",
                   ifelse(Player == "Hugh Duffy", "Veterans",
                   ifelse(Player == "Johnny Evers", "Veterans",
                   ifelse(Player == "Luke Appling", "BBWAA",
                   ifelse(Player == "Ray Schalk", "Veterans",
                   ifelse(Player == "Roger Bresnahan", "Veterans",
                   ifelse(Player == "Roberto Clemente", "BBWAA",
                   ifelse(Player == "Lou Gehrig", "BBWAA",
                   ifelse(Player == "Lou Criger", "Veterans",
                   ifelse(Player == "Shoeless Joe Jackson", "Veterans",
                   ifelse(Player == "Bill Killefer", "Veterans",
                   ifelse(Player == "Billy Sullivan", "Veterans",
                          votedBy))))))))))))))))) %>%
  mutate(Player = ifelse(playerID == "griffke02", "Ken Griffey Jr", Player)) %>%
  inner_join(primary_position, by = "playerID")

```

```{r time series mess, warning=FALSE, message=FALSE}

# Below are mainly for time series analysis

# For player name, debute, and playerID conversion
player_df <- read_csv(file = "Data/People2022.csv")

# Creates Player column to ease merging with other df's
player_df <- player_df %>% mutate(Player = str_c(nameFirst,
                                                 nameLast,
                                                 sep = " "))

# For updated pitching data to get accurate innings pitched totals
pitcherTimeSeries_df <- read_csv(file = "Data/Pitching2022.csv")

# vector of playerID's who've played in 2017 or beyond
pitcherTimeSeries_df_2017onwards <- pitcherTimeSeries_df %>%
  group_by(playerID) %>%
  filter(yearID >= 2017) %>% 
  pull(playerID) %>%
  unique()

# Applies vector to main data set and filters, creates IP column
pitcherTimeSeries_df <- pitcherTimeSeries_df %>% 
  filter(playerID %in% pitcherTimeSeries_df_2017onwards) %>%
  mutate(IP = round(IPouts/3, 1))

# Merges Player bio df with median innings pitched df
avg_ip_df <- pitcherTimeSeries_df %>%
  group_by(playerID) %>% 
  summarise_at(vars(IP), list(MedianIP = median)) %>%
  inner_join(player_df, by = "playerID") %>%
  mutate(played2017plus = T)

# For time series pitch frequency covariates
pitch_arsenal_df <- rbind(read_csv(file = "Data/pitch_arsenals_2017.csv"),
                          read_csv(file = "Data/pitch_arsenals_2018.csv"),
                          read_csv(file = "Data/pitch_arsenals_2019.csv"),
                          read_csv(file = "Data/pitch_arsenals_2020.csv"),
                          read_csv(file = "Data/pitch_arsenals_2021.csv"),
                          read_csv(file = "Data/pitch_arsenals_2022.csv"))


# We are making the assumption that players retain primary pitch type prior to the 2017 StatCast season.

# Create universal name variable to join with tommyJohn_df 
pitch_arsenal_df <- pitch_arsenal_df %>% mutate(Player = str_c(first_name,
                                                               last_name,
                                                               sep = " ")) %>%
  group_by(Player) %>%
  summarise_at(vars(n_ff,
                    n_si,
                    n_fc,
                    n_sl,
                    n_ch,
                    n_cu,
                    n_fs), list(mean))

# For dates and player who had Tommy John surgery
tommyJohn_df <- read_csv(file = "Data/Tommy John Surgery List (@MLBPlayerAnalys) - TJ List.csv")

# Gets rid of spaces in col names
names(tommyJohn_df) <- str_replace_all(names(tommyJohn_df),
                                       c(" " = "_" , "," = "" ))

# Merges the TJ, pitch arsenal, player bio, and IP data. Indicates censored
timeseries_df <- full_join(pitch_arsenal_df, tommyJohn_df, by = "Player") %>%
  mutate(TJ_Surgery_Date = mdy(TJ_Surgery_Date)) %>%
  full_join(avg_ip_df, by = "Player") %>%
  filter(played2017plus == T) %>%
  mutate(HadTJ = ifelse(is.na(TJ_Surgery_Date), 0, 1)) %>%
  mutate(Censored = ifelse(HadTJ == "No" & finalGame < "2022-09-01",
                           "Censored",
                           "Non-Censored")) %>%
  mutate(PrimaryPitch = ifelse(n_ff > n_si 
                               & n_ff > n_fc
                               & n_ff > n_sl
                               & n_ff > n_ch
                               & n_ff > n_cu
                               & n_ff > n_fs, "4seamFastball",
                        ifelse(n_si > n_ff 
                               & n_si > n_fc
                               & n_si > n_sl
                               & n_si > n_ch 
                               & n_si > n_cu
                               & n_si > n_fs, "Sinker",
                        ifelse(n_fc > n_ff 
                               & n_fc > n_si 
                               & n_fc > n_sl
                               & n_fc > n_ch
                               & n_fc > n_cu
                               & n_fc > n_fs, "Cutter",
                        ifelse(n_sl > n_ff 
                               & n_sl > n_fc
                               & n_sl > n_si
                               & n_sl > n_ch
                               & n_sl > n_cu
                               & n_sl > n_fs, "Slider",
                        ifelse(n_ch > n_ff
                               & n_ch > n_fc
                               & n_ch > n_sl
                               & n_ch > n_si
                               & n_ch > n_cu
                               & n_ch > n_fs, "Change-up",
                        ifelse(n_cu > n_ff 
                               & n_cu > n_fc
                               & n_cu > n_sl
                               & n_cu > n_ch
                               & n_cu > n_si
                               & n_cu > n_fs, "Curveball",
                        "Splitter"))))))) %>%
  mutate(numDaysUntilTJ = ifelse(!is.na(TJ_Surgery_Date),
                                 TJ_Surgery_Date - debut,
                                 finalGame - debut)) %>%
  filter(is.na(numDaysUntilTJ) == T | numDaysUntilTJ > 0) %>%
  mutate(Fast_Off_Break = ifelse(PrimaryPitch == "4seamFastball"
                           | PrimaryPitch == "Cutter"
                           | PrimaryPitch == "Sinker", "Fastball",
                           ifelse(PrimaryPitch == "Splitter"
                           | PrimaryPitch == "Change-up", "Offspeed", "Breakingball"))) %>%
  filter(!is.na(n_ff)) 

# Final data frame to be used for analysis
final_time_series_df <- timeseries_df %>%
  select(1, 50, 55, 51, 67, 68, 70, 78, 80, 76, 79)


```

```{r EDA445}

# firstbump?

# Summary Stats, HR by hall of fame status
tapply(PositionPlayerHOF_df$HR, PositionPlayerHOF_df$wein, summary)

# Summary Stats, H by hall of fame status
tapply(PositionPlayerHOF_df$H, PositionPlayerHOF_df$wein, summary)

# Summary Stats, RBI by hall of fame status
tapply(PositionPlayerHOF_df$RBI, PositionPlayerHOF_df$wein, summary)

# Boxplot comparing homerun totals in non-hall of famers to hall of famers
hr_by_HOF <- ggplot(data = PositionPlayerHOF_df,
                    mapping = aes(x = wein, y = HR)) +
  geom_boxplot()

# Boxplot comparing hit totals in non-hall of famers to hall of famers
hits_by_HOF <- ggplot(data = PositionPlayerHOF_df,
                      mapping = aes(x = wein, y = H)) + 
  geom_boxplot()

# Boxplots stratified by number of mvp's, grouped by hof, on number of hr totals 
 ggplot(data = PositionPlayerHOF_df,
                     mapping = aes(x = wein, y = HR, color = most_valuable_player)) + 
  geom_boxplot()

# Pairs plots
pairs(PositionPlayerHOF_df[,c(4, 5, 8, 9, 10, 12, 14, 21, 23, 24, 27, 41)])

get_corr_matrix(PitcherHOF_df[c("W", "G", "SV", "ER", "HR", "SO", "IPouts", "ERA", "WHIP")])

get_corr_matrix(PositionPlayerHOF_df[c("G", "AB", "H", "2B", "3B", "HR", "RBI", "SB", "BB", "SO", "IBB", "HBP", "SH", "SF", "GIDP", "AVG", "OBP", "SLG")])

get_corr_matrix <- function(data) {
  data[is.na(data)] <- 0
  
  res <- cor(data.frame(lapply(data, as.numeric)))

  corrplot(res, type = "upper",
         tl.col = "black", tl.srt = 90)
}

# Counting number of players elected into the hall before and after major awards

hall_df_eda <- hall_df %>%
  group_by(playerID) %>%
  subset(select = c(1, 2, 3, 7, 8)) %>%
  filter(category == "Player") %>%
  mutate(before_mvp = ifelse(yearID < 1931, 1, 0))  %>%
  mutate(before_as = ifelse(yearID < 1933, 1, 0))  %>%
  mutate(before_cy = ifelse(yearID < 1956, 1, 0))  %>%
  mutate(before_gg = ifelse(yearID < 1957, 1, 0))  %>%
  mutate(before_rr = ifelse(yearID < 1976, 1, 0))  %>%
  mutate(before_ss = ifelse(yearID < 1980, 1, 0))

ggplot(data = hall_df_eda, 
       mapping = aes(x = yearID,
                     fill = inducted)) +
  geom_histogram(col=I("black")) +
  geom_vline(xintercept = 1931, col = "blue") +
  geom_vline(xintercept = 1933, col = "red") +
  geom_vline(xintercept = 1956, col = "forestgreen") +
  geom_vline(xintercept = 1957, col = "gold3") +
  geom_vline(xintercept = 1976, col = "purple") +
  geom_vline(xintercept = 1980, col = "grey50") +
  theme_classic() +
  labs(x = "Year", y = "Inducted or Dropped from Ballot",
       title = "Introduction of Awards Overlayed by Hall of Fame Class") +
  annotate(geom="text", x=2005, y=300, label="Introduction of MVP",
              color="blue") + 
  annotate(geom="text", x=2005, y=280, label="Introduction of All Star",
              color="red") + 
  annotate(geom="text", x=2005, y=260, label="Introduction of Cy Young",
              color="forestgreen") + 
  annotate(geom="text", x=2005, y=240, label="Introduction of Gold Glove",
              color="gold3") + 
  annotate(geom="text", x=2005, y=220, label="Introduction of Rolaids Relief Man",
              color="purple") +
  annotate(geom="text", x=2005, y=200, label="Introduction of Silver Slugger",
              color="grey50")
  
      
# Find the proportion of total hall of fame electees before each award was introduced

total_hall_before_mvp <- mean(hall_df_eda$before_mvp)
total_hall_before_as <- mean(hall_df_eda$before_as)
total_hall_before_cy <- mean(hall_df_eda$before_cy)
total_hall_before_gg <- mean(hall_df_eda$before_gg)
total_hall_before_rr <- mean(hall_df_eda$before_rr)
total_hall_before_ss <- mean(hall_df_eda$before_ss)

t(tibble(Before_MVP = total_hall_before_mvp,
       Before_AS = total_hall_before_as,
       Before_Cy = total_hall_before_cy,
       Before_GG = total_hall_before_gg,
       Before_RR = total_hall_before_rr,
       Before_SS = total_hall_before_ss))

# Cooks distance ----

row.names(PositionPlayerHOF_df) <- PositionPlayerHOF_df$playerID

bad_glm_pos <- glm(as.factor(wein) ~ G + AB + R + H + HR + RBI + SB + BB +
                                     PrimaryLg + all_star + 
                                     most_valuable_player + AVG + OBP + SLG +
                                     Steroids + nice_guy_awards + WAR + Pos +
                                     gold_glove + silver_slugger +
                                     hank_aaron_award + Steroids:HR +
                                     H:Steroids,
                   data = PositionPlayerHOF_df,
                   family = "binomial")

plot(bad_glm_pos, which = 4)


```

```{r Cox Proportional Hazards Analysis}

library(survival)
library(timereg)
library(foreign)
library(msm)
library(KMsurv)

# Preliminary analysis of distribution of primary pitches
with(final_time_series_df, table(Fast_Off_Break))

# Preliminary analysis of distribution of primary pitches
with(final_time_series_df, table(PrimaryPitch))

# Of pitchers who threw breaking balls primarily, number who had TJ vs not
length(final_time_series_df$numDaysUntilTJ[final_time_series_df$Fast_Off_Break == "Breakingball" & final_time_series_df$HadTJ == "Yes"])
length(final_time_series_df$numDaysUntilTJ[final_time_series_df$Fast_Off_Break == "Breakingball" & final_time_series_df$HadTJ == "No"])

# Of pitchers who threw Fastballs primarily, number who had TJ vs not
length(final_time_series_df$numDaysUntilTJ[final_time_series_df$Fast_Off_Break == "Fastball" & final_time_series_df$HadTJ == "Yes"])
length(final_time_series_df$numDaysUntilTJ[final_time_series_df$Fast_Off_Break == "Fastball" & final_time_series_df$HadTJ == "No"])

# Of pitchers who threw Offspeed pitches primarily, number who had TJ vs not
length(final_time_series_df$numDaysUntilTJ[final_time_series_df$Fast_Off_Break == "Offspeed" & final_time_series_df$HadTJ == "Yes"])
length(final_time_series_df$numDaysUntilTJ[final_time_series_df$Fast_Off_Break == "Offspeed" & final_time_series_df$HadTJ == "No"])


KM_3pitch <- survfit(Surv(numDaysUntilTJ, HadTJ) ~ Fast_Off_Break,
                     data = final_time_series_df)
print(KM_3pitch)

km_3pitch_plot <- plot(KM_3pitch, col = c("red", "blue", "green"),
                       lwd = 2, xlab = "Time (days)",
                       main = "", ylab = "Survival Probability")
```


```{r}
library(RColorBrewer)

PitcherHOF_df %>% 
  mutate(wein = ifelse(wein == 1, "HoF", "No HoF")) %>% 
  ggplot() +
  geom_density_ridges(aes(x = SO, y = wein, fill = wein)) +
  scale_fill_manual(values = RColorBrewer::brewer.pal(n=2,"Paired")) +
  theme_ridges() +
  theme(legend.title = element_blank()
        ,legend.position = c(0.83, 0.8)) +
  labs(x = "Strikeouts", y = "", title = "Distribution of Strikeouts (pitchers)")

PositionPlayerHOF_df %>% 
  mutate(wein = ifelse(wein == 1, "HoF", "No HoF")) %>% 
  ggplot() +
  geom_density_ridges(aes(x = HR, y = wein, fill = wein)) +
  scale_fill_manual(values = RColorBrewer::brewer.pal(n=2,"Paired")) +
  theme_ridges() +
  theme(legend.title = element_blank()
        ,legend.position = c(0.83, 0.8)) +
  labs(x = "Home Runs", y = "", title = "Distribution of Homeruns (positional players)")
```

```{r}
legend("topright", c("Fastball", "Offspeed", "BreakingBall"), col=c("blue", "red", "green"),
 lwd=c(2, 2), cex=0.6,bty="n")


final_time_series_filtered_df <- final_time_series_df %>%
  filter(HadTJ == 1)

box_plot <- ggplot(data = final_time_series_filtered_df, 
                   mapping = aes(x = numDaysUntilTJ,
                                 color = PrimaryPitch)) +
  geom_boxplot()

point_plot <- ggplot(data = final_time_series_filtered_df, 
                     mapping = aes(x = numDaysUntilTJ,
                                   y = MedianIP,
                                   color = Fast_Off_Break)) +
  geom_point()
```

```{r}
library(rvest)

# Players to model on -- if they retired in the last 5 years
recent_players <- player_df %>% 
  filter(finalGame >= Sys.Date() - (365 * 5) & playerID %in% c((pitching_df %>% group_by(playerID) %>% filter(length(unique(yearID)) >= 10) %>% pull(playerID) %>% unique()), (batting_df %>% group_by(playerID) %>% filter(length(unique(yearID)) >= 10) %>% pull(playerID) %>% unique())) & !(playerID %in% (hall_df %>% pull(playerID) %>% unique())))

# Check if they are currently active or not based on if they are on a team
# Around 28% of the players in this list are still active -- based on baseball reference

# recent_players_info <- data.frame(matrix(ncol = 4))
# 
# colnames(recent_players_info) <- c("player", "active", "current_team", "info")
# 
# url <- "https://www.baseball-reference.com/players/%s.shtml"
# 
# for (player in recent_players$playerID) {
#   result = tryCatch({
#     str_player <- paste0(str_sub(player, 1, 1), "/", player)
#     status <- read_html(sprintf(url, str_player)) %>% 
#       html_node("#meta") %>% 
#       html_node("div:nth-child(2)") %>% 
#       html_nodes("p:nth-child(5)")
#   }, warning = function(warning_condition) {
#       print('warning')
#   }, error = function(error_condition) {
#       recent_players_info <- rbind(recent_players_info, c(player, F, NA, "Player not found."))
#   }, finally={
#       status_text <- str_replace_all(html_text(status), "\\n", "")
#   
#       if (str_detect(html_text(status), "Born")) {
#         recent_players_info <- rbind(recent_players_info, c(player, F, NA, status_text))
#       } else {
#         recent_players_info <- rbind(recent_players_info, c(player, T, html_text(html_node(status, "a")), status_text))
#       }
#   })
#   
#   
#   Sys.sleep(5)
# }

recent_players <- recent_players %>%
  left_join(recent_players_info , by = c("playerID" = "player")) %>%
  mutate(active = active == "TRUE", finalgame_before_2022 = finalGame <= "2022-04-07")

recent_players %>%
  select(active, finalgame_before_2022) %>%
  summarize_all(mean)

write.csv(recent_players, "recent_players.csv")
```

```{r try models}

# Pitcher Model selection ----

# Trying to find best predictors, including awards introduced after 1933
lm_pitcher_subset_bad <- regsubsets(as.factor(wein) ~ W + L + G + IP + ERA +
                                                      all_star + WHIP + SO +
                                                      gold_glove + WAR + SV +
                                                      cy_young_award +
                                                      Steroids +
                                                      most_valuable_player + 
                                                      pitching_triple_crown +
                                                      rolaids_relief_man_award +
                                                      nice_guy_awards,
                                    data = PitcherHOF_df)

summary(lm_pitcher_subset_bad)

# Gold glove and Cy Young only added to 7 and 8 term models. Why does do the reliever awards do so well?

# Trying to find best predictors, only including awards introduced before 1933
lm_pitcher_subset_good <- regsubsets(as.factor(wein) ~ W + L + G + IP + ERA +
                                                       all_star + WHIP + SO +
                                                       WAR + Steroids + SV +
                                                       most_valuable_player + 
                                                       pitching_triple_crown +
                                                       nice_guy_awards,
                                     data = PitcherHOF_df)

summary(lm_pitcher_subset_good)

# Why is the saves column so good at predicting?

# Position Player Model selection ----

# Trying to find best predictors, including awards introduced after 1933
lm_position_subset_bad <- regsubsets(as.factor(wein) ~ G + AB + R + H + HR +
                                                       RBI + SB + BB +
                                                       PrimaryLg + all_star +
                                                       most_valuable_player +
                                                       AVG + OBP + SLG +
                                                       Steroids + 
                                                       nice_guy_awards + WAR +
                                                       Pos + gold_glove + 
                                                       silver_slugger +
                                                       hank_aaron_award +
                                                       Steroids:HR + H:Steroids,
                                     data = PositionPlayerHOF_df)
summary(lm_position_subset_bad)

# Notice silver slugger and gold glove never relevant. This may justify dropping them.

# Trying to find best predictors, only including awards introduced before 1933
lm_position_subset_good <- regsubsets(as.factor(wein) ~ G + AB + R + H +                                                        RBI + SB + BB +
                                                        PrimaryLg + all_star*WAR +
                                                        most_valuable_player +
                                                        AVG + OBP + SLG +
                                                        HR:Steroids + WAR:Steroids +
                                                        nice_guy_awards + HR*WAR +
                                                        Pos + votedBy,
                                      data = PositionPlayerHOF_df, 
                                      really.big = T)
summary(lm_position_subset_good)

PositionPlayerHOF_df$Pos <- relevel(as.factor(PositionPlayerHOF_df$Pos), ref = "DH")
ideal_model <- step(glm(wein ~ G + AB + R + H + RBI + SB + BB + PrimaryLg +
                          all_star*WAR + most_valuable_player + 
                          AVG + OBP + SLG + HR:Steroids + WAR:Steroids +
                          nice_guy_awards + HR*WAR + Pos + votedBy,
                        data = PositionPlayerHOF_df, family = "binomial"),
                    direction = "both", k = 2)
```

